title: Simon Winther
description: A blog where I talk about my experience studying Computer Science and also show off some projects or other programming activities off.
theme: just-the-docs
repository: "simonsejse/blog"

url: https://simonsejse.github.io/blog

color_scheme: dark

compress_html:
  blanklines: true
mathjax:
  source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
  config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'

collections:
  programming:
    permalink: "/:collection/:path/"
    output: true
 

just_the_docs:
  collections:
    programming:
      name: Programmering
      
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  console:
    title: Console output
    color: pink
