title: Simon Winther
description: A blog where I talk about my experience studying Computer Science and also show off some projects or other programming activities off.
theme: just-the-docs

url: https://simonsejse.github.io/blog

color_scheme: dark

compress_html: 
  blanklines: true

# LaTeX rendering via "katex" (KaTeX, default) or "mathjax" (MathJax) or "none" / "off" (NO rendering)
latex: katex


callouts:
  warning:
    title: Warning
    color: red
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
